version: "3.9"

services:
    backend:
        image: antwon-dj/dev.backend
        container_name: antwon-dj.dev_backend
        build:
            context: ../../../backend
            dockerfile: dev.Dockerfile
        command: chalice local --stage local --host=0.0.0.0 --port=8000
        networks:
            - internal-network
        ports:
            - 8000:8000
        volumes:
            - ../../../.aws.config:/root/.aws/config:ro
            - ../../../backend/.chalice:/backend/.chalice
            - ../../../backend/app.py:/backend/app.py
            - ../../../backend/mypy.ini:/backend/mypy.ini
            - ../../../backend/chalicelib:/backend/chalicelib

    client:
        image: antwon-dj/dev.client
        container_name: antwon-dj.dev_client
        build:
            context: ../../../client
            dockerfile: dev.Dockerfile
        command: yarn dev
        networks:
            - internal-network
        ports:
            - 3000:3000
            - 3001:3001
        volumes:
            - ../../../client/__mocks__:/client/__mocks__
            - ../../../client/.storybook:/client/.storybook
            - ../../../client/public:/client/public
            - ../../../client/src:/client/src
            - ../../../client/tests:/client/tests
            - ../../../client/.env.local:/client/.env.local
            - ../../../client/.eslintrc:/client/.eslintrc
            - ../../../client/jest.config.js:/client/jest.config.js
            - ../../../client/next-env.d.ts:/client/next-env.d.ts
            - ../../../client/next.config.js:/client/next.config.js
            - ../../../client/tsconfig.json:/client/tsconfig.json

networks:
    internal-network:
        driver: bridge
