from typing import Dict, Any

from chalicelib.models.spotify_api.album import SpotifyAlbum
from chalicelib.models.spotify_api.artist import SpotifyArtist
from chalicelib.models.spotify_api.image import SpotifyImage
from chalicelib.models.spotify_api.track import SpotifyTrack, SpotifyTrackFormatted


def get_example_track(uri: str = "spotify:track:6N1K5OVVCopBjGViHs2IvP") -> SpotifyTrack:
    return SpotifyTrack(
        album=SpotifyAlbum(
            album_type="single",
            artists=[
                SpotifyArtist(
                    external_urls={"spotify": "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V"},
                    href="https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
                    id="6eUKZXaKkcviH0Ku9w2n3V",
                    name="Ed Sheeran",
                    type="artist",
                    uri="spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
                ),
                SpotifyArtist(
                    external_urls={"spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"},
                    href="https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
                    id="06HL4z0CvFAxyc27GXpf02",
                    name="Taylor Swift",
                    type="artist",
                    uri="spotify:artist:06HL4z0CvFAxyc27GXpf02",
                ),
            ],
            type="album",
            uri="spotify:album:0vkAczpFKCazPKaoLtnBr0",
            available_markets=[
                "AD",
                "AE",
                "AG",
                "AL",
                "AM",
                "AO",
                "AR",
                "AT",
                "AU",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BN",
                "BO",
                "BR",
                "BS",
                "BT",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CD",
                "CG",
                "CH",
                "CI",
                "CL",
                "CM",
                "CO",
                "CR",
                "CV",
                "CW",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FJ",
                "FM",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GH",
                "GM",
                "GN",
                "GQ",
                "GR",
                "GT",
                "GW",
                "GY",
                "HK",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IQ",
                "IS",
                "IT",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KR",
                "KW",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MG",
                "MH",
                "MK",
                "ML",
                "MN",
                "MO",
                "MR",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NE",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PG",
                "PH",
                "PK",
                "PL",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RO",
                "RS",
                "RW",
                "SA",
                "SB",
                "SC",
                "SE",
                "SG",
                "SI",
                "SK",
                "SL",
                "SM",
                "SN",
                "SR",
                "ST",
                "SV",
                "SZ",
                "TD",
                "TG",
                "TH",
                "TJ",
                "TL",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UA",
                "UG",
                "US",
                "UY",
                "UZ",
                "VC",
                "VE",
                "VN",
                "VU",
                "WS",
                "XK",
                "ZA",
                "ZM",
                "ZW",
            ],
            external_urls={"spotify": "https://open.spotify.com/album/0vkAczpFKCazPKaoLtnBr0"},
            href="https://api.spotify.com/v1/albums/0vkAczpFKCazPKaoLtnBr0",
            id="0vkAczpFKCazPKaoLtnBr0",
            images=[
                SpotifyImage(
                    height=640, width=640, url="https://i.scdn.co/image/ab67616d0000b27389aff4625958eac8d16535c7"
                ),
                SpotifyImage(
                    height=300, width=300, url="https://i.scdn.co/image/ab67616d00001e0289aff4625958eac8d16535c7"
                ),
                SpotifyImage(
                    height=64, width=64, url="https://i.scdn.co/image/ab67616d0000485189aff4625958eac8d16535c7"
                ),
            ],
            name="The Joker And The Queen (feat. Taylor Swift)",
            release_date="2022-02-11",
            release_date_precision="day",
            total_tracks=1,
        ),
        artists=[
            SpotifyArtist(
                external_urls={"spotify": "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V"},
                href="https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
                id="6eUKZXaKkcviH0Ku9w2n3V",
                name="Ed Sheeran",
                type="artist",
                uri="spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
            ),
            SpotifyArtist(
                external_urls={"spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"},
                href="https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
                id="06HL4z0CvFAxyc27GXpf02",
                name="Taylor Swift",
                type="artist",
                uri="spotify:artist:06HL4z0CvFAxyc27GXpf02",
            ),
        ],
        available_markets=[
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
        ],
        disc_number=1,
        duration_ms=185422,
        explicit=False,
        external_ids={"isrc": "GBAHS2200019"},
        external_urls={"spotify": "https://open.spotify.com/track/6N1K5OVVCopBjGViHs2IvP"},
        href="https://api.spotify.com/v1/tracks/6N1K5OVVCopBjGViHs2IvP",
        id="6N1K5OVVCopBjGViHs2IvP",
        is_local=False,
        name="The Joker And The Queen (feat. Taylor Swift)",
        popularity=86,
        preview_url="https://p.scdn.co/mp3-preview/a0d12ef3cfe7b4b1a3339cf6f4d66f2ab6ce40da?cid=f6a9c5777c3d47c6a2054c"
        "14c8c557ff",
        track_number=1,
        type="track",
        uri=uri,
    )


def get_example_api_track(uri: str = "spotify:track:6N1K5OVVCopBjGViHs2IvP") -> Dict[str, Any]:
    return {
        "album": {
            "album_type": "single",
            "artists": [
                {
                    "external_urls": {"spotify": "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V"},
                    "href": "https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
                    "id": "6eUKZXaKkcviH0Ku9w2n3V",
                    "name": "Ed Sheeran",
                    "type": "artist",
                    "uri": "spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
                },
                {
                    "external_urls": {"spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"},
                    "href": "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
                    "id": "06HL4z0CvFAxyc27GXpf02",
                    "name": "Taylor Swift",
                    "type": "artist",
                    "uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02",
                },
            ],
            "available_markets": [
                "AD",
                "AE",
                "AG",
                "AL",
                "AM",
                "AO",
                "AR",
                "AT",
                "AU",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BN",
                "BO",
                "BR",
                "BS",
                "BT",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CD",
                "CG",
                "CH",
                "CI",
                "CL",
                "CM",
                "CO",
                "CR",
                "CV",
                "CW",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FJ",
                "FM",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GH",
                "GM",
                "GN",
                "GQ",
                "GR",
                "GT",
                "GW",
                "GY",
                "HK",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IQ",
                "IS",
                "IT",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KR",
                "KW",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MG",
                "MH",
                "MK",
                "ML",
                "MN",
                "MO",
                "MR",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NE",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PG",
                "PH",
                "PK",
                "PL",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RO",
                "RS",
                "RW",
                "SA",
                "SB",
                "SC",
                "SE",
                "SG",
                "SI",
                "SK",
                "SL",
                "SM",
                "SN",
                "SR",
                "ST",
                "SV",
                "SZ",
                "TD",
                "TG",
                "TH",
                "TJ",
                "TL",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UA",
                "UG",
                "US",
                "UY",
                "UZ",
                "VC",
                "VE",
                "VN",
                "VU",
                "WS",
                "XK",
                "ZA",
                "ZM",
                "ZW",
            ],
            "external_urls": {"spotify": "https://open.spotify.com/album/0vkAczpFKCazPKaoLtnBr0"},
            "href": "https://api.spotify.com/v1/albums/0vkAczpFKCazPKaoLtnBr0",
            "id": "0vkAczpFKCazPKaoLtnBr0",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b27389aff4625958eac8d16535c7",
                    "width": 640,
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e0289aff4625958eac8d16535c7",
                    "width": 300,
                },
                {"height": 64, "url": "https://i.scdn.co/image/ab67616d0000485189aff4625958eac8d16535c7", "width": 64},
            ],
            "name": "The Joker And The Queen (feat. Taylor Swift)",
            "release_date": "2022-02-11",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:0vkAczpFKCazPKaoLtnBr0",
        },
        "artists": [
            {
                "external_urls": {"spotify": "https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V"},
                "href": "https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V",
                "id": "6eUKZXaKkcviH0Ku9w2n3V",
                "name": "Ed Sheeran",
                "type": "artist",
                "uri": "spotify:artist:6eUKZXaKkcviH0Ku9w2n3V",
            },
            {
                "external_urls": {"spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"},
                "href": "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
                "id": "06HL4z0CvFAxyc27GXpf02",
                "name": "Taylor Swift",
                "type": "artist",
                "uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02",
            },
        ],
        "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
        ],
        "disc_number": 1,
        "duration_ms": 185422,
        "explicit": False,
        "external_ids": {"isrc": "GBAHS2200019"},
        "external_urls": {"spotify": "https://open.spotify.com/track/6N1K5OVVCopBjGViHs2IvP"},
        "href": "https://api.spotify.com/v1/tracks/6N1K5OVVCopBjGViHs2IvP",
        "id": "6N1K5OVVCopBjGViHs2IvP",
        "is_local": False,
        "name": "The Joker And The Queen (feat. Taylor Swift)",
        "popularity": 86,
        "preview_url": "https://p.scdn.co/mp3-preview/a0d12ef3cfe7b4b1a3339cf6f4d66f2ab6ce40da?cid=f6a9c5777c3d47c6a20"
        "54c14c8c557ff",
        "track_number": 1,
        "type": "track",
        "uri": uri,
    }


def get_example_track_formatted(
    song_uri: str = "spotify:track:6N1K5OVVCopBjGViHs2IvP",
    song_name: str = "The Joker And The Queen (feat. Taylor Swift)",
) -> SpotifyTrackFormatted:
    return SpotifyTrackFormatted(
        song_uri=song_uri,
        song_artist="Ed Sheeran, Taylor Swift",
        song_name=song_name,
        song_album_url="https://i.scdn.co/image/ab67616d0000b27389aff4625958eac8d16535c7",
    )


def get_example_empty_track_formatted() -> SpotifyTrackFormatted:
    return SpotifyTrackFormatted(
        song_uri="empty_song_uri",
        song_artist="Add Songs to Queue",
        song_name="No Song Playing",
        song_album_url="https://www.pngkey.com/png/detail/15-159637_black-box-with-question-mark-png.png",
    )
