name: backendCI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install black flake8 pytest mypy pytest-mypy pytest-cov pytest-lazy-fixture
        pip install -r requirements.txt
    - name: Lint with black
      run: |
        cd backend
        black --check -l 120 .
    - name: Lint with flake8
      run: |
        cd backend
        flake8 --max-line-length 120
    - name: Type check with mypy
      run: |
        cd backend
        mypy app.py
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Test with pytest and collect coverage
      run: |
        pytest --mypy --cov backend/
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
