on:
  push:
    branches:
      - main
name: Deploy branch to Chalice
jobs:
  deploy:
    name: dev-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        pip install -r requirements.txt
    - name: Lint with black
      run: |
        black -l --check 120 .
    - name: Test with pytest
      run: |
        pytest
    - name: chalice deploy
      uses: jayef0/chalice-extended-action@release-v0.2.1
      env:
        WORKING_DIRECTORY: backend
        REQUIREMENTS_FILE: backend/requirements.txt
        OPERATION: deploy
        STAGE: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-2
